package protocol

const (
	PACKET_CLIENTBOUND_KICK uint8 = iota
	PACKET_CLIENTBOUND_MAP_UPDATE
	PACKET_CLIENTBOUND_VIEW_UPDATE
	PACKET_CLIENTBOUND_GUI_UPDATE
)

const (
	PACKET_SERVERBOUND_JOIN uint8 = iota
	PACKET_SERVERBOUND_INPUT
)

const (
	BITFLAG_INPUT_LEFT uint8 = 1 << iota
	BITFLAG_INPUT_RIGHT
	BITFLAG_INPUT_UP
	BITFLAG_INPUT_DOWN
	BITFLAG_INPUT_LMB
	BITFLAG_INPUT_RMB
	BITFLAG_MOUSE_MOVE
)

const (
	ENTITY_TYPE_DEFAULT uint8 = iota
	ENTITY_TYPE_SHIP
)
